export const actionTypes = {
    ADD_USER: 'ADD_USER',
    ADD_EMAIL: 'ADD_EMAIL',
    ADD_DATE_OF_BIRTH: 'ADD_DATE_OF_BIRTH',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    ADD_NEW_USER: 'ADD_NEW_USER',
    DELETE_USER: 'DELETE_USER'
}
